---
title: "Syllabus EC202: Fall 2018"
author: "James Woods"
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course Description

The official description of the course is:

 > A study of factors affecting the level of national income: the essentials of money and banking; the role of government expenditure and taxation in achieving economic stability, growth and development; international monetary issues including exchange rates and the balance of payments.

It is my intent to give you a basket of tools that you can use after the final exam to better understand the news, your later economics courses.


## Key Dates

+ Final Exam: December 4th,	10:15-12:05
+ Midterm 1: October 18th
+ Midterm 2: November 13th
+ Last Day to Withdraw or Change Grade Option: November 11th
+ Holiday: November 22nd

Exams will be given on those days and at those times only.  I do not give make up, early or late exams.  The final is required.  You will receive a failing grade if you don't take it.

If you have a DRC compensation and would normally schedule an exam in the testing center, you must schedule your exam so that it starts at the same time as the class.

## Contact Information

Communication will be handled through slack https://PSUec202Fall2018.slack.com. You should have received an invitation, if not, just go to that URL and use your @pdx.edu email to sign up. There are reasonable help documents to get you started. https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-users

Slack will be used for IM, email and forum style communication.  It even handles phone calls. If you have a question about course material or the course itself, ask in one of the channels. If you have a personal message that is not intended for others, send a direct message. The group has global do not disturb hours of 10pm - 8am.  If you would like something different, alter your personal settings.

Please note that I am not online all the time, and when I am online I will prioritize well-phrased questions with sufficient detail.  I tend to ignore general complaints, questions that can be answered by reading the syllabus or using the search bar.  

I will not react to questions in the day prior to an exam under most circumstances. I am just trying to protect my workload from student procrastination.  *If your study strategy is to cram the night before, you are on your own.* 


Office Hours:

+ My office is in CH 241-O.
+ Drop in office hours are Monday 12:00-1:00  through the last week of class. There is no need to make an appointment for these hours -- just come.
+ If you can’t attend regular office hours, please check my calendar https://woodsj.youcanbook.me/. I will make a limited number of 15 minute slots available each week. If you make an appointment and fail to show up without first canceling, I will penalize your final exam score two points.  

My in-person office hours may need to be moved to a different location because of construction in Cramer Hall.  I will put something on slack if this is necessary.

# Textbook and Other Resources

I have assigned Krugman, Paul R., and Robin Wells. Macroeconomics ed. 5., Worth Publishers, 2018.(ISBN-10: 1-319-09875-4).  This textbook is amazingly overpriced.  I will not be assigning questions from the chapters, so feel free to purchase one of the earlier editions of the book.

The 3rd edition can be found at a more reasonable price and can even be rented for less than \$20. Just remember that you are responsible for keeping track of the differences in chapter numbering and the differences between editions. You can find the table of contents for the 5th edition here (https://www.macmillanlearning.com/Catalog/product/macroeconomics-fifthedition-krugman/tableofcontents#tab).

## Netiquette

Since we will be having some online interaction, we should be clear
about what we should and should not do.

In class, I can see what is going on at all times.  In the online
environment, I can't see everything and I can't react as quickly to
what I do see.  Students are expected to be particularly trustworthy both in terms of their own conduct, and in reporting inappropriate conduct to me.

I will not tolerate profanity, obscenity, or remarks intended to
discount or dismiss either a person or his or her point of view. If your inappropriate message is in the public forum, I will warn you
once in that public space. If you continue with inappropriate conduct
in the public spaces, your access to them will be denied for the rest
of the term. If your inappropriate conduct is in private, a student code of conduct violation complaint may be filed. 
 
## D2L

You will turn in homework assignments, either "assignment" or "quizzes" depending on the format of the homework, both of which you will find under activites. An up to date calendar of homework assignments can be found in the left-hand side of the landing page.  Homework will typically be due Friday at noon and I will always give you at least a week between assignment of homework and the due date.

The course landing page will also have links to the course slack group and the slides I create for class.

# Assessments and Grade Policy

Your grade in the class will be based on your performance on the midterms, final exam, homework assignments and in-class quizzes.  

+ Final Exam (30%)
+ Midterm 1 (20%)
+ Midterm 2 (20%)
+ In-class quizzes (20%)
+ Homework (10%)

## Exams

Exams will be closed note and closed book.  Problems will be multiple choice questions but each question may require a significant amount of work.

Students will be assigned seats and photo ID will be required for all exams. You will only be allowed a writing implement and a calculator.  No headphones, phones, smart watches, internet connected devices, or other material will be allowed.  All backpacks will be stored at the front or side of the classroom.  If we see a phone, we will take your exam, you will receive a zero, and you will be sent to the dean of student life.

The seating chart for the exam will be released on slack just before the exam to make it easier to find your seat.

## In-class quizzes

There may be a pop quiz each class meeting. In-class quizzes are intended to be a check on if you completed the required reading and if you have reviewed the previous meetings's material. They are graded on a pass/no-pass basis and will not be returned, but a key will be provided. 

While it may be tempting to avoid class because of the easy access to the lecture slides, this is typically a quick path to a low grade.

## Homework

Homework will be due, at most, weekly and will turned in via D2L either as a D2L "quiz", or as a pdf or word document through D2L "assignment" function.  

D2L quizzes are intended to be done online without the help of others.  

If the homework is turned in through the assignment function they must be turned in as either word or pdf documents. Unreadable or corrupt files will be given a zero. 

Do not write the assignments out by hand and then turn in a photo in pdf form.  D2L does not handle this well, often freezing the browser. We will simply give you a zero on the assignment if you do this.

# Topics

A detailed reading schedule will be announced as we progress both in class and in slack.

+ What is Economics (Ch 1 and 2)

+ Supply and Demand (Ch 3 - 5)

+ Introduction to Macroeconomics (Ch 6):  There are similarities and differences between microeconomics and macroeconomics

+ Measuring the Economy (Ch 7 and 8): Our measurements of output, inflation and unemployment are based on surveys, sophisticated models, and even "analysis's best guess".

+ The Long-Run (Ch 9 and 10)

+ The Short-Run (Ch 11 and 12)

+ Policy Interventions: Fiscal (Ch 13): This is looks at how the government, mostly congress and the president, can intervene in the economy by altering taxes and government spending.

+ Policy Interventions: Monetary and Financial (Ch 14 - 16):  This looks at how our monetary authority, the Federal Reserve, can intervene in the economy by manipulating the money supply and interest rates.

+ Trade and International Finance (Ch 18)

+ Current Events (Ch 17)


# Other Rules

+ Please be aware that federal, state, and PSU policies require faculty members to report any instances of sexual harassment, sexual violence and/or other forms of prohibited discrimination. Similarly, PSU faculty are required to file a report if they have reasonable cause to believe that a child with whom they come into contact has suffered abuse, or that any person with whom they come into contact has abused a child. If you would rather share information about these experiences with an employee who does not have these reporting responsibilities and can keep the information confidential, please contact one of the following campus resources (or visit https://www.pdx.edu/sexual-assault/sites/www.pdx.edu.sexual-assault/files/Revised%20SA-IPVResourceHandout%20long%20version-revised%20.pdf):

    + Women’s Resource Center (503-725-5672)
    + Queer Resource Center (503-725-9742)
    + Center for Student Health and Counseling (SHAC): 1880 SW 6th Ave, (503) 725-2800
    + Student Legal Services: 1825 SW Broadway, (SMSU) M343, (503) 725-4556

    For more information about the applicable regulations please complete the required student module Creating a Safe Campus in your D2L.


+ Begging for grades will result in an immediate lowering of your course grade by a full letter grade.
  
+ When completing online quizzes or other assignments, you may use your book, wiki, calculator, spreadsheets, notes, or other resources as long as it is not another student or person.  *The work must be authentically and genuinely your own. In other words, if you are copying answers you found online, it is not your work.*

+ Go to office hours at the first sign of trouble -- not as a last resort.

+ In this classroom, we support and value diversity.  To do so requires that we:

    + Respect the dignity and essential worth of all individuals
    + Promote a culture of respect toward all individuals
    + Respect the privacy, property, and freedom of others
    + Reject bigotry, discrimination, violence, or intimidation of any kind
    + Practice personal and academic integrity and expect it from others
    + Promote the diversity of opinions, ideas, and backgrounds, which is the lifeblood of a university

    For additional information, please see the Office of Affirmative Action \& Equal Opportunity at https://www.pdx.edu/diversity/welcome-to-global-diversity-inclusion.


+ Accommodations are collaborative efforts between students, faculty, and the Disability Resource Center.  If you have a documented disability and require accommodation, you must arrange to meet with the course instructor prior to or within the first week of the term.  The documentation of your disability must come in writing from the Disability Resource Center (Faculty letter).  

+ PSU values diversity and inclusion; we are committed to fostering mutual respect and full participation for all students. My goal is to create a learning environment that is equitable, useable, inclusive, and welcoming. If any aspects of instruction or course design result in barriers to your inclusion or learning, please notify me. The Disability  Resource Center (DRC) provides reasonable accommodations for students who encounter barriers in the learning environment. 

    If you have, or think you may have, a disability that may affect your work in this class and feel you need accommodations, contact the Disability Resource Center to schedule an appointment and initiate a conversation about reasonable accommodations. The DRC is located in 116 Smith Memorial Student Union, 503-725-4150, drc@pdx.edu, https://www.pdx.edu/drc.

+ Academic honesty is expected and required of students enrolled in this course.  Suspected academic dishonesty in this course will be handled according to the procedures set out in the Student Code of Conduct.

+ I am sympathetic to family emergencies but you must inform me as soon as possible. If the notice is verbal, please email me with your understanding of our agreement. All agreements have to be in writing.


Link to this syllabus https://github.com/woodsjam/Course-Intro-Macroeconomics.  There is a branch for each term.  Be sure to choose the correct branch to see the current syllabus.  
